### ISSUE TITLE
How to use mixAttributes?

### ISSUE THREAD

**Issue by Jehu** [soyjavi/monocle#1]
Hi, 

first: thank you for monocle. It's lightweight and easy to learn.
Netherless i've some questions, because docs are a bit too lightweight ;-)

How can i use mixAttribute (as uses in example model on http://monocle.tapquo.com/) in a view?

I've tried in model

```
...
    @fullname: ->
        "#{ident}, #{city}"
...
```

in view

```
    template: 
        """
        <li>full name: {{fullname}}</li>
        """
```

but i get no output for the variable"fullname"

Can you show me how to use this please?

**Comment by soyjavi** [comment]
modelX.fullname() (it's a method)

**Comment by Jehu** [comment]
Thank you for the hint.

Can't get it work like it's described in documentation. Here is how i get it to work:

mixed attribute in model

```
    fullname: ->
        @ident + ', ' + @city
```

At on the documentation on website it's describet to put an @ before the function name. Also the template-syntax is described like so 

```
"#{placeholder1} - #{placeholder2}"
```

which i can't get to work. So i've just used string concatenation.

Usage of attribute method in mustache template, one must call the function, like @soyjavi said:

```
class TerritoryV extends Monocle.View
    container: "article#territories-list ul"
    template:
        """
        <li>{{fullname()}}</li>
        """
```
