### ISSUE TITLE
I can't compile using grunt

### ISSUE THREAD

**Issue by noelrocha** [soyjavi/monocle#3]
Running "grunt default" gives the following error output: 

Loading "grunt.js" tasks and helpers...ERROR

> > TaskError: Unable to read "package/component.json" file (Error code: ENOENT).
> > <WARN> Task "default" not found. Use --force to continue. </WARN>

Aborted due to warnings.

---

Where is the component.json file?

**Comment by basoko** [comment]
Hi, 

You can find the package folder here: https://github.com/soyjavi/package-monocle
