### ISSUE TITLE
Not works without scope?

### ISSUE THREAD

**Issue by dgdavid** [soyjavi/monocle#5]
Hi,

Excuse me if I'm wrong, but it seems that the classes don't work if are defined within a scope. Is possible?

For example, with

``` coffee
class Task extends Monocle.Model
    @fields "name", "description", "type", "done"

Task.create name: "Learn CoffeeScript", type: "Personal"
```

I get an error

```
Uncaught ReferenceError: Task is not defined
```

While with

``` coffee
class __Model.Task extends Monocle.Model
    @fields "name", "description", "type", "done"

__Model.Task.create name: "Learn CoffeeScript", type: "Personal"
```

Works fine

**Comment by soyjavi** [comment]
Do you how it works coffeescript?? if you use Task.create in other file …. Task doesn't exists :/

**Comment by dgdavid** [comment]
Ups! Sorry I didn't know, mea culpa. Thanks.
