### ISSUE TITLE
Mailing list for questions

### ISSUE THREAD

**Issue by noelrocha** [soyjavi/monocle#6]
Hi Guys,

is there any mailing list for some questions regarding the monocle usage?

Im trying to use the Controller routes. Is it related to Lungo navigation?

Thanks

**Comment by soyjavi** [comment]
Yes!

https://groups.google.com/forum/#!forum/amazing_monocle

**Comment by qtechnology** [comment]
Hola, una pregunta, no puedo usar templates con mustache pero siempre me manda error porque no puede eliminar los saltos de linea, la función replace en vez de reemplazar está agregando luego del salto de linea, ayudaaaaa ):
