### ISSUE TITLE
Version 1.0.2 off of official homepage not loading correctly in Chrome 26

### ISSUE THREAD

**Issue by RickCarlino** [soyjavi/monocle#9]
Hi,

When I tried to use the monoclejs file from the download link on the monocle homepage, Chrome spit out this error:
"
Uncaught SyntaxError: Unexpected identifier monocle.js:17
"
Using version 1.0.3 cleared out this issue, but I thought it was worth noting for those who are having the same issue.

Thanks for all the work you put in to this project, Javi- it looks great so far.

**Comment by soyjavi** [comment]
Use bower install monocle (v.1.0.4)
